version: '3.4'

services:
  mssql:
    image: microsoft/mssql-server-linux:latest
    volumes:
      - mssql-db-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: Y
      MSSQL_PID: Express
      SA_PASSWORD: StrongP@ssword
      MSSQL_MEMORY_LIMIT_MB: 3072
    ports:
      - "1433:1433"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092

  elasticsearch:
        image:  docker.elastic.co/elasticsearch/elasticsearch:7.10.0
        expose:
            - 9200
        ports:
            - 9200:9200
        restart: always
        environment:
          - xpack.monitoring.enabled=true
          - xpack.watcher.enabled=false
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
          - discovery.type=single-node
          - ELASTICSEARCH_USERNAME=elastic
          - ELASTICSEARCH_PASSWORD=search  
        volumes:
          - elasticsearch-db-data:/var/opt/elasticsearch/data
  kibana:
        container_name: kibana
        image: docker.elastic.co/kibana/kibana:7.10.0
        ports:
          - 5601:5601
        depends_on:
          - elasticsearch
        environment:
          - ELASTICSEARCH_URL=http://localhost:9200
          - ELASTICSEARCH_USERNAME=elastic
          - ELASTICSEARCH_PASSWORD=search
        restart: always
  jaeger: 
        image: jaegertracing/all-in-one:latest
        ports:
          - "5775:5775/udp"
          - "6831:6831/udp"
          - "6832:6832/udp"
          - "5778:5778"
          - "16686:16686"
          - "14268:14268"
          - "9411:9411"
volumes:
    mssql-db-data:
    elasticsearch-db-data: